### Regional HELM Script (not supposed to be modified by application team)
HELM_CHART_VERSION=1.0.0
HELM_TEMPLATE_REPO=ssh://git.ap.manulife.com:8080/rsf/rsf-helm-template.git
# refer to https://confluence.ap.manulife.com/display/FE/RSF+HELM+Template
HELM_TEMPLATE_BRANCH=release/v1.0.5.SR1
### Application team customizable settings
# Depends on target deploy namespace
K8S_TARGET_NAMESPACE=ns-mua-training
# Depends on where you put your HELM values files
K8S_PATH=k8s
emailRecipientList=kaiski_k_yang@manulife.com
EMAIL_RECIPIENT_LIST=kaiski_k_yang@manulife.com
