### AKS cluster configuration (not supposed to be modified by application team)
# the value you can find from  https://confluence.ap.manulife.com/display/HKDO/AKS+setup+for+AKS+Jenkins+Pipeline
AZURE_SERVICE_PRINCIPAL_SECRET_ID=AKS_HK_PROD_APP
AZURE_SERVICE_PRINCIPAL_ID=8d8b0934-d699-40ef-9537-32e2c4aa4e42
AZURE_TENANT_ID=5d3e2773-e07f-4432-a630-1a0f68a28a05
AZURE_SUBSCRIPTION_ID=aa5598d5-ed35-4885-aefb-805c3cca99eb
AZURE_RESOURCE_GROUP=SEA-HKG-AKSUAT-Production-01
AZURE_AKS_CLUSTER_NAME=aks-sea-hkg-uat
AZURE_KEYVAULT_NAME=akv-sea-hkg-uat