### AKS cluster configuration (not supposed to be modified by application team)
# the value you can find from  https://confluence.ap.manulife.com/display/HKDO/AKS+setup+for+AKS+Jenkins+Pipeline
AZURE_SERVICE_PRINCIPAL_SECRET_ID=AZ_SPN_EAS_HKG_NONPROD
AZURE_SERVICE_PRINCIPAL_ID=e91a7a16-47fb-4b8b-9488-21bd1208ac97
AZURE_TENANT_ID=5d3e2773-e07f-4432-a630-1a0f68a28a05
AZURE_SUBSCRIPTION_ID=96bdec4d-beee-4317-8e6d-06fc6b76cb79
AZURE_RESOURCE_GROUP=EAS-HKG-AKSDEV-NonProduction-01
AZURE_AKS_CLUSTER_NAME=aks-eas-hkg-dev
AZURE_KEYVAULT_NAME=akv-eas-hkg-dev

### CI 
skipUploadArtifactory=false
skipDeploy=false